### PR TITLE
Add support for approximate synchronization.

### LINKED ISSUE #4: Indigo onCalibrateTopic: stuck in infinite loop
I'm getting stuck in this **while** loop of node.cpp:

```
    sync.registerCallback(boost::bind(&synchronizationCallback, boost::ref(promise), _1, _2));

    // Run a background spinner for the callback queue.
    ros::AsyncSpinner spinner(1, &queue);
    spinner.start();

    ROS_INFO_STREAM("Done creating background spinner.");

    while (true) {  **<== I get stuck here**
    if (!node_handle.ok()) return false;
    if (future.wait_for(boost::chrono::milliseconds(100)) == boost::future_status::ready) break;
    }
    ROS_INFO_STREAM("Done waiting for the future.");
```

The synchronizationCallback is never called. I think this means the node is not receiving the cloud_topic and image_topic messages, but I've double-checked that the camera_pose_calibration node is subscribed correctly and the camera topics are active. I have a fork of the repo [here](https://github.com/AndyZe/camera_pose_calibration/blob/indigo/src/example_cam_cal.cpp) if you want to see exactly what my service client looks like.

### PR DESCRIPTION
**Pull request by de-vri-es**
Adds support for approximate synchronization between point cloud and color image from topics.

May fix #4.

### CODE REVIEW

**Comment by de-vri-es** [comment]
@AndyZe can you try this branch? To use the approximate synchronization you can set the parameter `sync_policy` to `approximate`.

**Comment by AndyZe** [comment]
@de-vri-es I appreciate it! It will be a little while before I can try because we're upgrading to Kinetic right now. In the short term for Indigo, I plan to use onCalibrateFile instead of onCalibrateTopic.

**Comment by AndyZe** [comment]
@de-vri-es I'm finally getting a chance to play with this. I forgot that my depth cloud was publishing at 30 Hz while the rgb stream was publishing at 15 Hz to save bandwidth, so you're probably right about the synchronization issue.

**Comment by de-vri-es** [comment]
Makes sense. I think supporting approximate synchronization is important anyway. I can't really test it though, so I'm interested to know if it works for you.

**Comment by AndyZe** [comment]
I'm sorry. I tried it quickly and it did not change the situation. I would like to work through my more fundamental issues with calibrateFile before worrying about camera synchronization.

**Comment by de-vri-es** [comment]
No problem. This can wait for a while. If I can find the time I may write something to purposefully publish unsynchronized data.

**Pull request closed without merging**
